// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHkQYbL9XqJdKWngmFTZikAxXM_tLbrY',
    appId: '1:941000988157:web:a99e51a9c8c69810343594',
    messagingSenderId: '941000988157',
    projectId: 'my-social-media-17ec0',
    authDomain: 'my-social-media-17ec0.firebaseapp.com',
    storageBucket: 'my-social-media-17ec0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsJYwFT8ImPuOH1O5NuvmVKmnDe_x6-M',
    appId: '1:941000988157:android:0bf9465d6bee45fc343594',
    messagingSenderId: '941000988157',
    projectId: 'my-social-media-17ec0',
    storageBucket: 'my-social-media-17ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCORvNCUSp3WoRQCKuMjqFDieZTd7BMN8w',
    appId: '1:941000988157:ios:139f5d2c1a73bdb3343594',
    messagingSenderId: '941000988157',
    projectId: 'my-social-media-17ec0',
    storageBucket: 'my-social-media-17ec0.appspot.com',
    iosBundleId: 'com.example.socialMediaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCORvNCUSp3WoRQCKuMjqFDieZTd7BMN8w',
    appId: '1:941000988157:ios:d6037d53c87dcf92343594',
    messagingSenderId: '941000988157',
    projectId: 'my-social-media-17ec0',
    storageBucket: 'my-social-media-17ec0.appspot.com',
    iosBundleId: 'com.example.socialMediaProject.RunnerTests',
  );
}
